export const FETCH_EMPLOYEE_START = 'FETCH_EMPLOYEE_START'
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS'
export const FETCH_EMPLOYEE_FAIL = 'FETCH_EMPLOYEE_FAIL'

export const ADD_EMPLOYEE_START = 'ADD_EMPLOYEE_START'
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL'

export const EDIT_EMPLOYEE_START = 'EDIT_EMPLOYEE_START'
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS'
export const EDIT_EMPLOYEE_FAIL = 'EDIT_EMPLOYEE_FAIL'

export const DEL_EMPLOYEE_START = 'DEL_EMPLOYEE_START'
export const DEL_EMPLOYEE_SUCCESS = 'DEL_EMPLOYEE_SUCCESS'
export const DEL_EMPLOYEE_FAIL = 'DEL_EMPLOYEE_FAIL'


export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE'
